# Example Render spec (optional)
services:
  - type: web
    name: mlb-picks-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://your-frontend.vercel.app,http://localhost:3000
